# Generated by Django 6.1.1 on 2026-09-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ai_follow_up',
            field=models.TextField(blank=True),
        ),
    ]
